### ISSUE TITLE
Consider a best practice YAML output `flow_style`

### ISSUE THREAD

**Issue by chrisbillowsMO** [MetOffice/CMEW#224]
**Is your feature request related to a problem? Please describe.**

As explored during #18, by default PyYAML varies the chosen output form style:

> By default, PyYAML chooses the style of a collection depending on whether it has nested collections. If a collection has nested collections, it will be assigned the block style. Otherwise it will have the flow style. 
>
> If you want collections to be always serialized in the block style, set the parameter default_flow_style of dump() to False. For instance,
>
>\>> print yaml.dump(yaml.load(document), default_flow_style=False)
>
> Source: [PyYaml Documentation](https://pyyaml.org/wiki/PyYAMLDocumentation)

The unpredictability of this default behaviour may make outputs harder to test.

**Describe the solution you'd like**

The working practices should be updated to recommend `yaml.dump` have `default_flow_style=False` passed.  An issue could also be raised to make this uniform across the current code.

**Describe alternatives you've considered**

It's possible that `default_flow_style=True` defaults to always using a `flow` style of output.  This didn't seem clear from the docs and wasn't tested thoroughly.  But if the `flow` style is preferred this may be an approach.  (See example of output below).

**Additional context**

YAML is written in with either the `flow` style or the `block` style.

Example: `flow` style:

```yml
{glossary: {GlossDiv: {GlossList: {GlossEntry: {Abbrev: 'ISO 8879:1986', Acronym: SGML,
          GlossDef: {GlossSeeAlso: [GML, XML], para: 'A meta-markup language, used
              to create markup languages such as DocBook.'}, GlossSee: markup, GlossTerm: Standard
            Generalized Markup Language, ID: SGML, SortAs: SGML}}, title: S}, title: example
      glossary}}
```

Example: `block` style

```yml
glossary:
  GlossDiv:
    GlossList:
      GlossEntry:
        Abbrev: ISO 8879:1986
        Acronym: SGML
        GlossDef:
          GlossSeeAlso:
          - GML
          - XML
          para: A meta-markup language, used to create markup languages such as DocBook.
        GlossSee: markup
        GlossTerm: Standard Generalized Markup Language
        ID: SGML
        SortAs: SGML
    title: S
  title: example glossary
```

Note also that the default behaviour seems to mix and match `flow` and `block` as in this section of default output:

```yml
Acronym: SGML
        GlossDef:
          GlossSeeAlso: [GML, XML]
          para: A meta-markup language, used to create markup languages such as DocBook.
        GlossSee: markup
```
