### ISSUE TITLE
Build and host rendered documentation on GitHub

### ISSUE THREAD

**Issue by ehogan** [MetOffice/CMEW#243]
## Reason for this issue

From the review of the CMEW repository by the Security Testing team:

> ## Description
> The repository under review currently contains references to internal Met Office URLs:
This information could provide an external threat actor with knowledge of internal Met Office services, however in isolation this information would be of little value.
> ## Solution
> Consider abstracting internal Met Office URLs into configuration which is stored outside of public repositories.

## Background

CMEW uses Sphinx to build the rendered HTML documentation from the [reStructuredText documentation](https://github.com/MetOffice/CMEW/tree/main/doc). The rendered HTML documentation is currently hosted on an [internal server](https://www-hc/~esmval/cmew/cmew-latest).

Once the CMEW repository has been made public, anyone will be able to view the documentation, regardless of whether they are a member of the MetOffice organisation in GitHub. Therefore, it will not be necessary to retain the rendered HTML documentation hosted on the [internal server](https://www-hc/~esmval/cmew/cmew-latest).

## Task

To create a GitHub Actions workflow that:

- [runs Sphinx to build the rendered HTML documentation](https://github.com/MetOffice/CMEW/wiki/Detailed-Working-Practices#build-the-documentation-locally)
- hosts the resulting HTML documentation via GitHub Pages

> [!NOTE]
> Use Sphinx rather than Jekyll to build the rendered HTML documentation.

## Acceptance criteria

- **Given** a GitHub Actions workflow named `gh-pages.yml`
- **When** there has been a push to `main` or the GitHub Actions workflow is triggered manually
- **Then** the rendered HTML documentation is built using Sphinx
- **And** the rendered HTML documentation is hosted via GitHub Pages such that they are available via https://metoffice.github.io/CMEW

## Additional information

Since we have GitHub Enterprise Cloud, documentation hosted via GitHub Pages can be private. The screenshot below shows the GitHub Pages settings for the CMEW repository. Only those with access to the CMEW repository will be able to see the documentation hosted via GitHub Pages:

![Image](https://github.com/user-attachments/assets/02cc9c70-6673-420d-bc14-2e2edb6e27ef)

Clicking on the "Configure" button at the bottom of the "GitHub Pages Jekyll" box returns:

```
# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

This would make a good starting point, but would need updating to use Sphinx rather than Jekyll.

## Useful Links

Follow the latest guidance at https://docs.github.com/en/pages.

## Details

- Estimate: Medium, suitable solo mission.
- Reviewer(s): Alistair, Emma
